services:
  php:
    image: php:8.2-fpm
    volumes:
      - "./:/var/www"
    environment:
      - APP_ENV=production
    command: sh -c "chown -R www-data:www-data /var/www/storage /var/www/database &&
           chmod -R 775 /var/www/storage &&
           chmod 664 /var/www/database/database.sqlite &&
           php-fpm"
  
  vite:
    image: node:22
    volumes:
      - "./:/var/www"
    working_dir: /var/www
    command: sh -c "npm install -g npm@11.4.0 && npm install --force && npm run build"

  nginx:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - "./:/var/www"
      - "./docker/nginx:/etc/nginx/conf.d"
    depends_on:
      - php
      - vite
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3